export const pantone = [
  { color: 'Black', hex: '#000' },
  { color: 'Oak', hex: '#C06F2E' },
  { color: 'Gray', hex: 'gray' },
  { color: 'Beige', hex: 'beige' },
  { color: 'Light Oak', hex: '#C7AA80' },
  { color: 'Walnut', hex: '#773F1A' },
  { color: 'White', hex: '#fff' },
  { color: 'Off White', hex: '#F2EEE3' },
  { color: 'Teal', hex: '#005553' },
  { color: 'Taupe', hex: '#AAA198' },
  { color: 'Brown', hex: '#4A2B0C' },
  { color: 'Silver', hex: 'silver' },
  { color: 'Light Beige', hex: 'beige' },
  { color: 'Gold', hex: '#d4af37' },
];
